spring.datasource.url=jdbc:postgresql://dpg-d42dibv5r7bs73dkn31g-a.oregon-postgres.render.com:5432/rizqconnect_db?sslmode=require
spring.datasource.username=rizqconnect_db_user
spring.datasource.password=Nmuzhvq6DHJ1XDOYF4ebBO9qtQpOHWIK
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

server.port=8080
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.web=INFO
spring.main.banner-mode=off
