spring.application.name=rizqconnects


# Supabase PostgreSQL Database

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#  JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT Settings (Your existing)

jwt.secret=fd7c1ab2f64f9e6a84be4e2b3a86e7cb47e63d4a55fa84cbb6f0a7d3c9c0b2e9e2a7a0b3c4d5e6f7a8b9c0d1e2f3a4b5
jwt.expiration=604800000
