# Production Database (Render PostgreSQL)


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# Disable SQL logs in production
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.web=INFO

# Security & performance tweaks (optional)
spring.main.banner-mode=off
spring.jpa.open-in-view=false
